### ISSUE TITLE
1.14 failure

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/CustomItemRegistry#6]
Spigot 1.14
CustomItemRecipes 1.4.5

On server start-up
```
[09:31:31] [Server thread/ERROR]: Could not load 'plugins/CustomItemRecipes-1.4.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/apache/commons/codec/DecoderException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:762) [spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/codec/DecoderException
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.DecoderException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.jar-2019-05-06-0312:git-Spigot-1eece4f-fe1199c]
        ... 6 more
```

**Comment by RoboMWM** [comment]
Interesting. It's probably clashing with another commons-io, or it was never shaded in (since I guess CB had one??)

Could verify by having CustomItemRecipes be the only plugin installed.

Thanks.

**Comment by RoboMWM** [comment]
Fixed in 1.4.6. And yes, the issue was spigot removed commons-io in the server jar in 1.14. https://github.com/MLG-Fortress/CustomItemRecipes/commit/3864c35dc77c1f79c3321fda68cb4bda7495f457

**Comment by SlimeDog** [comment]
I don't find the release, only sources. Also, api-version:1.14 will fail on 1.13.2. If you want to support both, it's api-version:1.13.

**Comment by RoboMWM** [comment]
Release is pending approval on bukkitdev. API-version 1.14 is used so it uses the 1.14 names instead of 1.13 names to support the variations in 1.14 items. I don't see any other reasonable way to do 1.13 compatibility without also dropping support for new 1.14 items.

**Comment by SlimeDog** [comment]
Thanks.
